make field final
eclipse/jkube pull request #1067
Opened 2021-10-25 10:31 UTC by nishantraut

## make field final

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2021-11-05 12:03 UTC, manusa requested changes

2021-11-05 12:03 UTC, manusa commented on jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/GitEnricher.java
> +    private final String GIT_REMOTE = "jkube.remoteName";
Should be `private static final`

2022-01-04 06:08 UTC, manusa commented
Hi @nishantraut, are you still working on this?

2022-01-04 07:59 UTC, nishantraut commented
Hi @manusa, Sorry for the delay review comment is fixed now.

2022-01-04 11:29 UTC, manusa approved these changes

2022-01-04 11:30 UTC, merged