chore (quickstarts/kit) : Port custom istio enricher quickstart to Gradle (#1252)
eclipse/jkube pull request #1457
Opened 2022-04-19 12:16 UTC by rohanKanojia

Fix #1252 

+ Add gradle quickstart for showcasing how to use custom enrichers with
kubernetes gradle plugin.
+ Add documentation in Enricher API section for information about using
    custom enrichers. Reference Custom Istio Enricher quickstarts added in kit
    modules in docs.

Signed-off-by: Rohan Kumar <rohaan@redhat.com>## Description

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [X] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2022-04-19 12:17 UTC, manusa commented
<!-- Eclipse JKube CI bot report -->

2022-04-29 11:00 UTC, manusa requested changes
https://github.com/rohanKanojia/jkube/pull/73

2022-05-02 04:24 UTC, manusa commented on quickstarts/kit/custom-istio-enricher-gradle/README.md
> +./gradlew ./gradlew publishToMavenLocal
AS you suggested, there's a typo here.

2022-05-02 04:25 UTC, manusa requested changes
Please, make sure you try my changes.
It seemed to work fine for me, but at some point, the k8sResource task was failing.

2022-05-02 07:54 UTC, rohanKanojia commented
I checked and k8sResource task seems to run okay for me.

2022-05-04 11:05 UTC, manusa approved these changes

2022-05-04 11:07 UTC, merged