refactor (jkube-kit/config/resource): Migrate all tests from JUnit4 to JUnit5 (#1553)
eclipse/jkube pull request #1664
Opened 2022-07-20 10:57 UTC by anurag-rajawat

## Description

Fixes #1553 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2022-07-20 10:57 UTC, manusa commented
<!-- Eclipse JKube CI bot report -->

2022-07-22 06:25 UTC, manusa commented on jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/ProcessorConfigTest.java
> +  void getValue(String testDesc, String key, TestConfig testConfig, String defaultValue, String expected) {
`key` is sort of ambiguous, what do you think of renaming to `propertyKey`?

2022-07-22 06:26 UTC, manusa commented on jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/ProcessorConfigTest.java
> +            Arguments.of("withValueInPropertiesAndDefaultValAndDefaultConfigShouldReturnValueInProperties", "prefix.name.one", TestConfig.ONE, "defaultValueOne", "oneInProp"),
Since you are providing the test descriptions as strings, maybe it's a good time to make them a little bit more readable ;)

2022-07-22 06:27 UTC, manusa requested changes
some minor changes requested, everything else looks great to me

2022-07-22 08:42 UTC, manusa approved these changes

2022-07-22 15:16 UTC, rohanKanojia approved these changes

2022-07-25 07:46 UTC, merged