(jkube-kit/enricher/api/) : Migrate tests from JMockit to Mockito
eclipse/jkube pull request #1748
Opened 2022-09-13 13:15 UTC by baruKreddy

Signed-off-by: baruKreddy [bhargavirkotha@gmail.com](mailto:bhargavirkotha@gmail.com)

Fixes https://github.com/eclipse/jkube/issues/1589

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2022-09-13 13:15 UTC, manusa commented
<!-- Eclipse JKube CI bot report -->

2022-09-14 06:09 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/EnricherConfigTest.java
>  import static org.junit.Assert.assertEquals;
replace this with assertj
```suggestion

```

2022-09-14 06:09 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/InitContainerHandlerTest.java
>  import static org.junit.Assert.fail;
```suggestion

```
Replace these assertions with assertj

2022-09-14 06:10 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
>  import static org.junit.Assert.assertTrue;
```suggestion

```

2022-09-14 06:10 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DaemonSetHandlerTest.java
>  import static org.junit.Assert.assertNotNull;
```suggestion

```

2022-09-14 06:11 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DeploymentHandlerTest.java
>  import static org.junit.Assert.assertNotNull;
```suggestion

```

2022-09-14 06:11 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/JobHandlerTest.java
>  import static org.junit.Assert.assertThrows;
```suggestion

```

2022-09-14 06:11 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ReplicaSetHandlerTest.java
>  import static org.junit.Assert.assertNotNull;
```suggestion

```

2022-09-14 06:13 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ReplicationControllerHandlerTest.java
>  import static org.junit.Assert.assertNotNull;
```suggestion

```

2022-09-14 06:13 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/StatefulSetHandlerTest.java
>  import static org.junit.Assert.assertNotNull;
```suggestion

```

2022-09-14 06:13 UTC, rohanKanojia requested changes
Looks good but JUnit assertions need to be replaced with assertj

2022-10-03 06:19 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/model/KindAndNameTest.java
> +        assertThat(kindAndName).isEqualTo(kindAndName).isNotNull().isEqualTo(kindAndName);
```suggestion
        assertThat(kindAndName).isEqualTo(kindAndName).isNotNull();
```

2022-10-03 06:22 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/InitContainerHandlerTest.java
> +        log = mock(KitLogger.class);
I think you can use SilentLogger here

2022-10-03 06:23 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/InitContainerHandlerTest.java
>          }
With `assertThatIllegalArgumentException` this try-catch block should not be needed

2022-10-03 06:23 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/InitContainerHandlerTest.java
> +                    .isThrownBy(() -> handler.appendInitContainer(builder, initContainer));
there should be a `hasMessage("")` method available to assert exception message

2022-10-03 06:27 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
> +        assertThat(containers.get(0).getImagePullPolicy()).isEqualTo("IfNotPresent");
```suggestion
        assertThat(containers)
            .isNotNull()
            .first(InstanceOfAssertFactories.type(Container.class))
            .hasFieldOrPropertyWithValue("name", "test-app")
            .hasFieldOrPropertyWithValue("image", "docker.io/test/test-app:1.2")
            .hasFieldOrPropertyWithValue("imagePullPolicy", "IfNotPresent");
```

2022-10-03 06:27 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
> +            assertThat( containers.get(0).getImage()).isEqualTo(testData[i+4]);
chain these assertions together

2022-10-03 06:27 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
> +        assertThat( containers.get(0).getImagePullPolicy()).isEqualTo("IfNotPresent");
chain these assertions together

2022-10-03 06:27 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
> +        assertThat(containers.get(0).getImagePullPolicy()).isEqualTo("IfNotPresent");
chain these assertions together

2022-10-03 06:28 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
> +        assertThat( containers.get(0).getVolumeMounts().get(0).getMountPath()).isEqualTo("/path/etc");
chain these assertions together

2022-10-03 06:28 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
> +        assertThat(containers.get(0).getVolumeMounts().get(0).getMountPath()).isEqualTo("/path/etc");
chain these assertions together

2022-10-03 06:36 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DaemonSetHandlerTest.java
> +        assertThat(daemonSet.getSpec().getTemplate().getSpec().getContainers()).isNotNull();
```suggestion
        assertThat(daemonSet)
            .hasFieldOrPropertyWithValue("metadata.name", "testing")
            .satisfies(d -> assertThat(d.getSpec().getTemplate().getSpec().getContainers()).isNotNull())
            .hasFieldOrPropertyWithValue("spec.template.spec.serviceAccountName", "test-account")
            .extracting(DaemonSet::getSpec)
            .extracting(DaemonSetSpec::getTemplate)
            .extracting(PodTemplateSpec::getSpec)
            .extracting(PodSpec::getVolumes)
            .asList()
            .first(InstanceOfAssertFactories.type(Volume.class))
            .hasFieldOrPropertyWithValue("name", "test")
            .hasFieldOrPropertyWithValue("hostPath.path", "/test/path");
```

2022-10-03 06:36 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DeploymentHandlerTest.java
> +        assertThat(deployment.getSpec().getTemplate().getSpec().getContainers()).isNotNull();
chain these assertions together

2022-10-03 06:36 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/JobHandlerTest.java
> +        assertThat(job.getSpec().getTemplate().getSpec().getContainers()).isNotNull();
chain these assertions together

2022-11-18 10:44 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
> +        assertThat( containers.get(0).getVolumeMounts().get(0).getMountPath()).isEqualTo("/path/etc");
Sorry, by chaining I meant doing this:
```java
        assertThat(containers.get(0).getVolumeMounts())
            .hasSize(1)
            .first(InstanceOfAssertFactories.type(VolumeMount.class))
            .hasFieldOrPropertyWithValue("mountPath", "/path/etc")
            .extracting(VolumeMount::getName)
            .isNull();
```

2022-11-18 10:44 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
> +        assertThat(containers.get(0).getVolumeMounts().get(0).getMountPath()).isEqualTo("/path/etc");
by chaining I meant using one `assertThat` statement

2022-11-18 10:55 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ServiceHandlerTest.java
> +        assertThat(services.get(0).getMetadata().getName()).isEqualToIgnoringCase("service-test");
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:55 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ServiceHandlerTest.java
> +        assertThat(services.get(0).getMetadata().getName()).isEqualToIgnoringCase("service-test");
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:55 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ServiceHandlerTest.java
> +        assertThat(services.get(0).getMetadata().getName()).isEqualToIgnoringCase("service-test");
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:55 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
> +        assertThat(probe.getHttpGet().getScheme()).isEqualTo("HTTP");
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:55 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
> +        assertThat(probe.getSuccessThreshold().intValue()).isEqualTo(1);
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:56 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
> +        assertThat( probe.getSuccessThreshold().intValue()).isEqualTo(1);
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:56 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
> +        assertThat(probe.getHttpGet().getScheme()).isEqualTo("HTTP");
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:56 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
> +        assertThat(probe.getTimeoutSeconds().intValue()).isEqualTo(5);
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:56 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
> +        assertThat(probe.getHttpGet()).isNull();
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:56 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
> +        assertThat(probe.getExec()).isNull();
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:56 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandlerTest.java
> +        assertThat(podTemplateSpec.getSpec().getContainers()).isNotNull();
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:56 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandlerTest.java
> +        assertThat(podTemplateSpec.getSpec().getContainers()).isNotNull();
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:56 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandlerTest.java
> +        assertThat(podTemplateSpec.getSpec().getContainers()).isNotNull();
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:56 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandlerTest.java
> +        assertThat(podTemplateSpec.getSpec().getContainers()).isNotNull();
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:56 UTC, rohanKanojia commented on jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandlerTest.java
> +                .getContainers().get(0).getImagePullPolicy()).isEqualTo("IfNotPresent");
Please chain assertions here. Try to do assertion using one `assertThat` statement like done in other places.

2022-11-18 10:57 UTC, rohanKanojia commented
@baruKreddy : Looks good overall apart from `assertThat` changes. Try to assert using single `assertThat` statement.

2022-11-25 12:52 UTC, baruKreddy commented
Creating new pull request as this is having conflicts with anurag's changes and quite confusing with assertions, closing this!

2022-11-25 12:52 UTC, closed without merging