refactor (org.eclipse.jkube.openshift.gradle.plugin): Migrate tests from JUnit4 to JUnit5 (#1582)
eclipse/jkube pull request #1826
Opened 2022-10-11 14:49 UTC by anurag-rajawat

## Description

Fixes #1582 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2022-10-11 14:49 UTC, manusa commented
<!-- Eclipse JKube CI bot report -->

2022-10-19 08:59 UTC, manusa requested changes

2022-10-19 08:59 UTC, manusa commented on gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtensionPropertyTest.java
> +  @ParameterizedTest(name = "{index}: {0}, returns {4}, or with property {1}={2} returns {3}")
This description doesn't seem to be right

2022-10-19 08:59 UTC, manusa commented on gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginRegisterTaskTest.java
> +  @ParameterizedTest(name = "{index}: {0}")
Maybe you can improve the description so that the test name reports what's actually happening (see method name).

2022-10-19 08:59 UTC, manusa commented on gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/TaskEnvironmentExtension.java
> +  File temporaryFolder;
Maybe keep this one private and provide a getter `getRoot` so there's no need for the extra-changes in the other extension-dependent test classes.

2022-10-28 06:44 UTC, anurag-rajawat commented
cc @rohanKanojia while re-requesting review from @manusa , review request from @rohanKanojia was automatically removed.

2022-10-28 06:49 UTC, anurag-rajawat commented on gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtensionPropertyTest.java
> +  @ParameterizedTest(name = "{index}: {0}, returns {4}, or with defaults {1}={2} returns {3}")
Fixed

2022-11-03 13:50 UTC, manusa approved these changes
LGTM, thx!

2022-11-04 10:17 UTC, rohanKanojia approved these changes

2022-11-04 10:19 UTC, merged