doc : FAQ now displayed in Gradle Plugin documentation (#2296)
eclipse/jkube pull request #2307
Opened 2023-07-25 13:16 UTC by Prafful-Rastogi

## Description

Fixes # (issue)

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] My code follows the style guidelines of this project
 - [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [ ] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2023-07-25 15:49 UTC, rohanKanojia commented
@Prafful-Rastogi : Thanks a lot! I can now see FAQ section both in maven and gradle plugins:

- https://ci.eclipse.org/jkube/job/Build/job/Documentation/job/PR-2307/3/artifact/docs-generated/kubernetes-gradle-plugin.html#faq
- https://ci.eclipse.org/jkube/job/Build/job/Documentation/job/PR-2307/3/artifact/docs-generated/kubernetes-maven-plugin.html#faq
- https://ci.eclipse.org/jkube/job/Build/job/Documentation/job/PR-2307/3/artifact/docs-generated/openshift-gradle-plugin.html#faq
- https://ci.eclipse.org/jkube/job/Build/job/Documentation/job/PR-2307/3/artifact/docs-generated/openshift-maven-plugin.html

2023-07-25 15:50 UTC, rohanKanojia approved these changes

2023-07-26 14:08 UTC, manusa requested changes

2023-08-04 09:46 UTC, manusa approved these changes

2023-08-04 10:03 UTC, merged