SecretEnricher getSecretsFromXmlConfig should return Collections.emptyList() instead of null
eclipse/jkube pull request #2554
Opened 2024-01-13 18:09 UTC by sankritimishra

## Description
 SecretEnricher getSecretsFromXmlConfig should return Collections.emptyList() instead of null 
Fixes #2530 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2024-01-13 18:09 UTC, manusa commented
<!-- Eclipse JKube CI bot report -->
<!-- METADATA {"pr":"2554","runId":"7514055298"} -->
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2554 (_2024-01-13T18:09:31Z_)

:gear: [JKube E2E Tests (7514055298)](https://github.com/jkubeio/ci/actions/runs/7514055298) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2554)](https://github.com/jkubeio/ci/actions/runs/7514055298/job/20456507739)

2024-01-17 18:44 UTC, rohanKanojia commented on jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/SecretEnricher.java
> +        return Optional.ofNullable(resourceConfig).map(resourceConfig1 -> Optional.ofNullable(resourceConfig1.getSecrets()).orElse(Collections.emptyList())).orElse(Collections.emptyList());
minor suggestion regarding formatting
```suggestion
        return Optional.ofNullable(getConfiguration().getResource())
            .map(rc -> Optional.ofNullable(rc.getSecrets())
                .orElse(Collections.emptyList()))
            .orElse(Collections.emptyList());
```

2024-01-18 05:12 UTC, rohanKanojia approved these changes

2024-01-23 09:52 UTC, rohanKanojia commented on jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/SecretEnricher.java
> +                .orElse(Collections.emptyList());
@sankritimishra : Sorry for the previous suggestion, [Optional.map](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#map-java.util.function.Function-) takes care of null values by returning an empty optional. You can directly map result without using nested Optional.ofNullable
```suggestion
        return Optional.ofNullable(getConfiguration())
            .map(Configuration::getResource)
            .map(ResourceConfig::getSecrets)
            .orElse(Collections.emptyList());
```

2024-01-25 11:24 UTC, manusa commented on jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/SecretEnricher.java
> +            .map(Configuration::getResource)
You're missing the required import for `org.eclipse.jkube.kit.enricher.api.model.Configuration`, the project won't compile unless you add it

2024-01-29 06:05 UTC, manusa requested changes
Hi, @sankritimishra 
This PR is getting really messy.
I suggest you start for scratch in a new branch (preferably named **different** to `master`).

Keep only these changes:
```java
   private List<SecretConfig> getSecretsFromXmlConfig() {
        return Optional.ofNullable(getConfiguration())
                .map(Configuration::getResource)
                .map(ResourceConfig::getSecrets)
                .orElse(Collections.emptyList());
    }
```

And try to open it on an IDE so that it can automatically fix the imports for you. At the moment I'm worried you're not even trying to compile the changed module in your local machine.

2024-01-31 19:14 UTC, closed without merging