Master soren
eclipse/jkube pull request #411
Opened 2020-09-28 12:45 UTC by manusa

## Description

Incremental PR for #375 (@sejacobsen) (Closes #375)

Added annotations so Router can be configured w/ TLS termination from the pom. Updated docs accordingly.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have implemented unit tests to cover my changes
 - [x] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] ~~I tested my code in Kubernetes~~
 - [x] I tested my code in OpenShift

2020-09-28 12:58 UTC, sejacobsen commented on kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
> +| `jkube.enricher.jkube-openshift-route.termination`
should be 'tlsTermination', no?

2020-09-28 12:59 UTC, sejacobsen commented on kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
> +          <termination>edge</termination>
<tlsInsecureEdgeTerminationPolicy>Allow</tlsInsecureEdgeTerminationPolicy>
          <tlsTermination>edge</tlsTermination>

2020-09-28 13:00 UTC, manusa commented on kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
> +| `jkube.enricher.jkube-openshift-route.termination`
:+1:  :facepalm:

2020-09-28 13:01 UTC, sejacobsen requested changes
Hi, please see my comments for suggested changes

2020-09-29 12:26 UTC, rohanKanojia approved these changes

2020-09-29 12:27 UTC, merged