Fix #624: Unable to override Image Name in Simple Dockerfile Mode with `jkube.generator.name`
eclipse/jkube pull request #629
Opened 2021-03-26 08:56 UTC by rohanKanojia

Fix #624 
Modify Mojos logic to consider image name configured from properties

## Description

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2021-03-29 10:33 UTC, manusa commented
<!-- Eclipse JKube CI bot report -->

2021-03-31 06:11 UTC, rohanKanojia commented
I think I removed usage of properties in DockerFileUtil. Now properties needed for defaultImageName are resolved in Mojos and resolvedImageName is passed to DockerFileUtil

2021-03-31 14:24 UTC, manusa commented on jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java
> +  public static String getValueFromProperties(Properties properties, String[] keys) {
Changing to:
```suggestion
  public static String getValueFromProperties(Properties properties, String... keys) {
```
will make life easier for method users and invocations will look clearer.

2021-03-31 14:24 UTC, manusa commented on jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java
> +        return properties.get(property).toString();
It might make sense to check if the property is not blank either

(get property, check if not null, check if not blank, return)

2021-03-31 14:41 UTC, manusa requested changes
see comment

2021-03-31 14:55 UTC, manusa approved these changes

2021-03-31 15:09 UTC, manusa commented
<!-- Eclipse JKube CI bot report -->

2021-03-31 15:32 UTC, manusa approved these changes

2021-03-31 15:46 UTC, merged